from typing import Any


exercise_categories: list[dict[str, Any]] = [
    {"id": 1, "name": "Strength Training"},
    {"id": 2, "name": "Weightlifting (Free Weights)"},
    {"id": 3, "name": "Compound Exercises"},
    {"id": 4, "name": "Powerlifting Focus"},
    {"id": 5, "name": "Bodyweight Exercises"},
    {"id": 6, "name": "Machine Exercises"},
    {"id": 7, "name": "Isolation Exercises"},
    {"id": 8, "name": "Core Strength"},
    {"id": 9, "name": "Calisthenics"},
]

exercises_list: list[dict[str, Any]] = [
    {"id": 1, "name": "Overhead Press (Shoulder Press)"},
    {"id": 2, "name": "Bicep Curl"},
    {"id": 3, "name": "Russian Twists"},
    {"id": 4, "name": "Squat"},
    {"id": 5, "name": "Crunches/Sit-ups"},
    {"id": 6, "name": "Glute Bridge/Hip Thrust"},
    {"id": 7, "name": "Leg Curl"},
    {"id": 8, "name": "Rear Delt Fly"},
    {"id": 9, "name": "Calf Raises"},
    {"id": 10, "name": "Good Mornings"},
    {"id": 11, "name": "Front Raise"},
    {"id": 12, "name": "Bench Press"},
    {"id": 13, "name": "Dumbbell Row"},
    {"id": 14, "name": "Plank"},
    {"id": 15, "name": "Tricep Extension"},
    {"id": 16, "name": "Leg Press"},
    {"id": 17, "name": "Shrugs"},
    {"id": 18, "name": "Lunges"},
    {"id": 19, "name": "Pull-up/Chin-up"},
    {"id": 20, "name": "Bent-Over Row"},
    {"id": 21, "name": "Deadlift"},
    {"id": 22, "name": "Lateral Raise"},
    {"id": 23, "name": "Leg Extension"},
    {"id": 24, "name": "Face Pulls"}
]


exercises_by_categories = {
    "Strength Training": [
        "Bench Press",
        "Bent-Over Row",
        "Bicep Curl",
        "Calf Raises",
        "Crunches/Sit-ups",
        "Deadlift",
        "Dumbbell Row",
        "Face Pulls",
        "Front Raise",
        "Glute Bridge/Hip Thrust",
        "Good Mornings",
        "Leg Curl",
        "Leg Extension",
        "Leg Press",
        "Lunges",
        "Overhead Press (Shoulder Press)",
        "Plank",
        "Pull-up/Chin-up",
        "Rear Delt Fly",
        "Russian Twists",
        "Shrugs",
        "Squat",
        "Tricep Extension",
    ],
    "Weightlifting (Free Weights)": [
        "Bench Press",
        "Bent-Over Row",
        "Bicep Curl",
        "Calf Raises",
        "Deadlift",
        "Dumbbell Row",
        "Face Pulls",
        "Front Raise",
        "Glute Bridge/Hip Thrust",
        "Good Mornings",
        "Lunges",
        "Overhead Press (Shoulder Press)",
        "Rear Delt Fly",
        "Shrugs",
        "Squat",
        "Tricep Extension",
        "Lateral Raise",
    ],
    "Compound Exercises": [
        "Bench Press",
        "Bent-Over Row",
        "Deadlift",
        "Dumbbell Row",
        "Face Pulls",
        "Glute Bridge/Hip Thrust",
        "Good Mornings",
        "Leg Press",
        "Lunges",
        "Overhead Press (Shoulder Press)",
        "Pull-up/Chin-up",
        "Squat",
    ],
    "Powerlifting Focus": ["Bench Press", "Deadlift", "Squat"],
    "Bodyweight Exercises": [
        "Calf Raises",
        "Crunches/Sit-ups",
        "Glute Bridge/Hip Thrust",
        "Lunges",
        "Plank",
        "Pull-up/Chin-up",
        "Russian Twists",
    ],
    "Machine Exercises": ["Leg Curl", "Leg Extension", "Leg Press"],
    "Isolation Exercises": [
        "Bicep Curl",
        "Calf Raises",
        "Glute Bridge/Hip Thrust",
        "Leg Curl",
        "Leg Extension",
        "Lateral Raise",
        "Front Raise",
        "Rear Delt Fly",
        "Shrugs",
        "Tricep Extension",
    ],
    "Core Strength": ["Crunches/Sit-ups", "Plank", "Russian Twists"],
    "Calisthenics": ["Crunches/Sit-ups", "Plank", "Pull-up/Chin-up"],
}

muscle_groups = {
    "Squat": [
        "Quadriceps",
        "Hamstrings",
        "Glutes",
        "Adductors",
        "Calves",
        "Lower Back",
        "Core",
    ],
    "Deadlift": [
        "Hamstrings",
        "Glutes",
        "Lower Back",
        "Trapezius",
        "Forearms",
        "Core",
        "Quadriceps",
    ],
    "Bench Press": ["Pectoralis Major", "Anterior Deltoids", "Triceps"],
    "Overhead Press (Shoulder Press)": [
        "Anterior Deltoids",
        "Lateral Deltoids",
        "Triceps",
        "Upper Trapezius",
        "Core",
    ],
    "Bent-Over Row": [
        "Latissimus Dorsi",
        "Rhomboids",
        "Trapezius",
        "Posterior Deltoids",
        "Biceps",
        "Forearms",
    ],
    "Pull-up/Chin-up": [
        "Latissimus Dorsi",
        "Biceps",
        "Forearms",
        "Rhomboids",
        "Trapezius",
    ],
    "Lunges": ["Quadriceps", "Hamstrings", "Glutes", "Calves", "Core"],
    "Leg Press": ["Quadriceps", "Hamstrings", "Glutes", "Calves"],
    "Leg Curl": ["Hamstrings"],
    "Leg Extension": ["Quadriceps"],
    "Calf Raises": ["Gastrocnemius", "Soleus"],
    "Bicep Curl": ["Biceps", "Brachialis", "Brachioradialis"],
    "Tricep Extension": ["Triceps"],
    "Lateral Raise": ["Lateral Deltoids"],
    "Front Raise": ["Anterior Deltoids"],
    "Rear Delt Fly": ["Posterior Deltoids", "Rhomboids", "Trapezius"],
    "Shrugs": ["Trapezius"],
    "Plank": [
        "Rectus Abdominis",
        "Obliques",
        "Transverse Abdominis",
        "Lower Back",
        "Shoulders",
        "Glutes",
    ],
    "Crunches/Sit-ups": ["Rectus Abdominis", "Obliques"],
    "Russian Twists": ["Obliques", "Rectus Abdominis", "Transverse Abdominis"],
    "Good Mornings": ["Hamstrings", "Glutes", "Lower Back"],
    "Face Pulls": ["Posterior Deltoids", "Rhomboids", "Trapezius", "Rotator Cuff"],
    "Glute Bridge/Hip Thrust": ["Glutes", "Hamstrings"],
    "Dumbbell Row": [
        "Latissimus Dorsi",
        "Rhomboids",
        "Trapezius",
        "Posterior Deltoids",
        "Biceps",
        "Forearms",
    ],
}

all_unique_muscle_groups: list[dict[str, Any]] = [
    {"id": 1, "name": "Adductors"},
    {"id": 2, "name": "Anterior Deltoids"},
    {"id": 3, "name": "Biceps"},
    {"id": 4, "name": "Brachialis"},
    {"id": 5, "name": "Brachioradialis"},
    {"id": 6, "name": "Calves"},
    {"id": 7, "name": "Core"},
    {"id": 8, "name": "Forearms"},
    {"id": 9, "name": "Gastrocnemius"},
    {"id": 10, "name": "Glutes"},
    {"id": 11, "name": "Hamstrings"},
    {"id": 12, "name": "Latissimus Dorsi"},
    {"id": 13, "name": "Lateral Deltoids"},
    {"id": 14, "name": "Lower Back"},
    {"id": 15, "name": "Obliques"},
    {"id": 16, "name": "Pectoralis Major"},
    {"id": 17, "name": "Posterior Deltoids"},
    {"id": 18, "name": "Quadriceps"},
    {"id": 19, "name": "Rectus Abdominis"},
    {"id": 20, "name": "Rhomboids"},
    {"id": 21, "name": "Rotator Cuff"},
    {"id": 22, "name": "Shoulders"},
    {"id": 23, "name": "Soleus"},
    {"id": 24, "name": "Transverse Abdominis"},
    {"id": 25, "name": "Trapezius"},
    {"id": 26, "name": "Triceps"},
    {"id": 27, "name": "Upper Trapezius"},
]


exercise_name_to_id = {ex["name"]: ex["id"] for ex in exercises_list}
exercise_category_to_id = {excat["name"]: excat["id"] for excat in exercise_categories}
muscle_group_to_id = {musclegroup["name"]: musclegroup["id"] for musclegroup in all_unique_muscle_groups}